# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './gui/estramo_gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1264, 1046)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fileinput = QtWidgets.QHBoxLayout()
        self.fileinput.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.fileinput.setSpacing(6)
        self.fileinput.setObjectName("fileinput")
        self.import_filename = QtWidgets.QLineEdit(self.centralwidget)
        self.import_filename.setObjectName("import_filename")
        self.fileinput.addWidget(self.import_filename)
        self.browse_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browse_button.sizePolicy().hasHeightForWidth())
        self.browse_button.setSizePolicy(sizePolicy)
        self.browse_button.setMaximumSize(QtCore.QSize(25, 16777215))
        self.browse_button.setObjectName("browse_button")
        self.fileinput.addWidget(self.browse_button)
        self.import_button = QtWidgets.QPushButton(self.centralwidget)
        self.import_button.setObjectName("import_button")
        self.fileinput.addWidget(self.import_button)
        self.verticalLayout.addLayout(self.fileinput)
        self.display = QtWidgets.QLabel(self.centralwidget)
        self.display.setText("")
        self.display.setObjectName("display")
        self.verticalLayout.addWidget(self.display)
        self.tools = QtWidgets.QHBoxLayout()
        self.tools.setObjectName("tools")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.tools.addItem(spacerItem)
        self.validate_button = QtWidgets.QPushButton(self.centralwidget)
        self.validate_button.setObjectName("validate_button")
        self.tools.addWidget(self.validate_button)
        self.verticalLayout.addLayout(self.tools)
        self.textOutput = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textOutput.sizePolicy().hasHeightForWidth())
        self.textOutput.setSizePolicy(sizePolicy)
        self.textOutput.setMinimumSize(QtCore.QSize(0, 27))
        self.textOutput.setMaximumSize(QtCore.QSize(16777215, 300))
        self.textOutput.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.textOutput.setObjectName("textOutput")
        self.verticalLayout.addWidget(self.textOutput)
        self.utility = QtWidgets.QHBoxLayout()
        self.utility.setObjectName("utility")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.utility.addItem(spacerItem1)
        self.clear_button = QtWidgets.QPushButton(self.centralwidget)
        self.clear_button.setObjectName("clear_button")
        self.utility.addWidget(self.clear_button)
        self.verticalLayout.addLayout(self.utility)
        self.verticalLayout.setStretch(1, 1)
        self.gridLayout.addLayout(self.verticalLayout, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1264, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Transformations"))
        self.import_filename.setText(_translate("MainWindow", "~/path/to/file.xml"))
        self.browse_button.setText(_translate("MainWindow", "..."))
        self.import_button.setText(_translate("MainWindow", "import"))
        self.validate_button.setText(_translate("MainWindow", "validate"))
        self.clear_button.setText(_translate("MainWindow", "clear log"))

